version: '3'

services:
  be-service:
    container_name: fashion-be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-service
    ports:
      - 8081:8081
      - 8787:8787

  postgres-service:
    image: postgres:9.6.10
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-volume:/data/postgres
    ports:
      - 5432:5432
      - 5433:5432
    restart: always

volumes:
  postgres-volume:
